### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by luyi670** [daliansky/Beelink-SER5-Hackintosh#24]
刚刚入手的 Ser5 max ,官方版本，直接用大神的 efi,好像无法启动，是有什么需要修改下吗？

**Comment by Kev1nFang** [comment]
理论不用修改，14.3.1 的直接进，EFI 没问题，从自己的安装方式排查吧

**Comment by luyi670** [comment]
好像是能启动，但每次都需要 10 分钟左右才能进去

**Comment by Kev1nFang** [comment]
你用的什么版本，我用 12.7.4也要 很长时间才能进
