### ISSUE TITLE
AppleALC_5800H.kext can work in minisforum 580D?

### ISSUE THREAD

**Issue by journeyaway** [daliansky/Beelink-SER5-Hackintosh#6]
HDMI Sound card can't working at minisforum 580D .This AppleALC_5800H.kext and "alcid=58" is OK?

**Comment by CHxCOOH** [comment]
btw, type-c dp alt mode also cannot output audio

**Comment by daliansky** [comment]
It's two completely different drivers, please don't apply
Currently, all beelink 5000 series sound cards have been perfectly driven, and this issue will be closed.
![Audio](https://raw.githubusercontent.com/daliansky/Beelink-SER5-Hackintosh/main/ScreenShots/Beelink-SER5-5800H_Micphone_OK.png)
