### ISSUE TITLE
这次新版的驱动能用内置MIC了

### ISSUE THREAD

**Issue by journeyaway** [daliansky/Beelink-SER5-Hackintosh#8]
<img width="478" alt="屏幕快照 2023-09-06 的 21 22 41 下午" src="https://github.com/daliansky/Beelink-SER5-Hackintosh/assets/96234663/8967380c-4a61-4a3f-be34-8d9c07e0f357">

内置MIC能用了，CODEC芯片采用CX11880的设备“NVRAM”中“boot-args”alcid=58要改为alcid=21

**Comment by daliansky** [comment]
alcid=21支持显示器音频输出吗？还有，这也要开个issue？
